name: hexcelon
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30
  cached_network_image: ^3.2.2
  camera: ^0.10.5+3
  dio: ^5.3.2
  file_picker: ^5.3.3
  flutter_datetime_picker_plus: ^2.0.1
  flutter_screenutil: ^5.8.4
  flutter_sound: ^9.2.13
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.6.0
  global_configuration: ^2.0.0-nullsafety.1
  google_sign_in: ^6.1.4
  hive_flutter: ^1.1.0
  image_editor_plus: ^0.2.5
  image_picker: ^1.0.2
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  keyboard_attachable: ^2.1.0
  logger: 1.1.0
  objectbox: ^2.2.0
  objectbox_flutter_libs: ^2.2.0
  path_provider: ^2.1.0
  percent_indicator: ^4.2.3
  permission_handler: ^10.4.3
  pinput: ^3.0.0
  provider: ^6.0.5
  scroll_to_index: ^3.0.1
  share_plus: ^7.1.0
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.1.11
  watcher: ^1.0.2

dev_dependencies:
  flutter_native_splash: ^2.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  build_runner: ^2.0.0
  objectbox_generator: ^2.2.0

flutter_native_splash:
  color: "#FFF6ED"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo.png
    icon_background_color: "#FFF6ED"
    image_dark: assets/images/logo.png
    icon_background_color_dark: "#FFF6ED"
  android: true
  ios: true
  web: true
  fullscreen: false
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# flutter pub run flutter_launcher_icons
# dart run flutter_native_splash:create

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/cfg/
  fonts:
    - family: Nova
      fonts:
        - asset: assets/fonts/400.otf
          weight: 400
        - asset: assets/fonts/500.otf
          weight: 500
        - asset: assets/fonts/600.otf
          weight: 600
        - asset: assets/fonts/700.otf
          weight: 700
        - asset: assets/fonts/800.otf
          weight: 800
        - asset: assets/fonts/900.otf
          weight: 900
