name: hexcelon
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  camera: ^0.10.5+9
  collection:
  dio: ^5.4.1
  file_picker: ^6.2.0
  flutter_datetime_picker_plus: ^2.1.0
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.6.7
  global_configuration: ^2.0.0-nullsafety.1
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  image: ^4.1.7
  image_editor_plus: ^1.0.5
  image_picker: ^1.0.7
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  keyboard_attachable: ^2.2.0
  logger: ^2.1.0
  objectbox: ^2.5.1
  objectbox_flutter_libs: ^2.5.1
  path_provider: ^2.1.2
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.0
  pinput: ^4.0.0
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  share_plus: ^7.2.2
  timeago: ^3.6.1
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.2.5
  watcher: ^1.1.0
  appinio_video_player: ^1.3.0
  chewie_audio: ^1.5.0
  audioplayers: ^6.0.0
  record: ^5.0.4
  video_editor: ^3.0.0
  fraction: ^5.0.2
  ffmpeg_kit_flutter_min: ^6.0.3
  firebase_dynamic_links: ^5.4.18
  firebase_core: ^2.27.1
  like_button: ^2.0.5
  device_info:
dependency_overrides:
  image: ^4.1.7
  js: ^0.7.1
  video_player_platform_interface: ^6.2.2

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  objectbox_generator: ^2.5.1

flutter_native_splash:
  color: "#FFF6ED"
  image: assets/images/logo.png
  android_12:
    image: assets/images/logo12.png
    icon_background_color: "#FFF6ED"
    image_dark: assets/images/logo12.png
    icon_background_color_dark: "#FFF6ED"
  android: true
  ios: true
  web: true
  fullscreen: false
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo2.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# flutter pub run flutter_launcher_icons
# dart run flutter_native_splash:create

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/cfg/
    - shorebird.yaml
  fonts:
    - family: Nova
      fonts:
        - asset: assets/fonts/400.otf
          weight: 400
        - asset: assets/fonts/500.otf
          weight: 500
        - asset: assets/fonts/600.otf
          weight: 600
        - asset: assets/fonts/700.otf
          weight: 700
        - asset: assets/fonts/800.otf
          weight: 800
        - asset: assets/fonts/900.otf
          weight: 900
