name: hexcelon
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.12.30
  cached_network_image: ^3.3.1
  camera: ^0.11.0
  collection:
  dio: ^5.4.3+1
  file_picker: ^8.0.5
  flutter_datetime_picker_plus: ^2.2.0
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  get_it: ^7.7.0
  global_configuration: ^2.0.0-nullsafety.1f
  google_sign_in: ^6.2.1
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  image: ^4.2.0
  image_editor_plus: ^1.0.6
  image_picker: ^1.1.2
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  logger: ^2.3.0
  objectbox: ^4.0.1
  objectbox_flutter_libs: ^4.0.1
  path_provider: ^2.1.3
  percent_indicator: ^4.2.3
  permission_handler: ^11.3.1
  pinput: ^5.0.0
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  share_plus: ^9.0.0
  timeago: ^3.6.1
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.3.0
  watcher: ^1.1.0
  flick_video_player: ^0.8.0
  chewie_audio: ^1.5.0
  audioplayers: ^6.0.0
  record: ^5.1.1
  video_editor:
    git:
      url: https://github.com/mitch2na/video_editor.git
      ref: master
  keyboard_attachable:
    git:
      url: https://github.com/adrienbaron/keyboard_attachable.git
      ref: master
  fraction: ^5.0.2
  ffmpeg_kit_flutter_min: ^6.0.3
  firebase_dynamic_links: ^6.0.1
  firebase_core: ^3.1.0
  like_button: ^2.0.5
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  objectbox_generator: ^4.0.1

flutter_native_splash:
  color: "#CCFD54"
  image: assets/images/logo-light.png

  color_android: "#CCFD54"
  color_dark_android: "#5441BF"
  color_ios: "#CCFD54"
  color_dark_ios: "#5441BF"

  image_android: assets/images/logo-light.png
  image_dark_android: assets/images/logo-dark.png
  image_ios: assets/images/logo-light.png
  image_dark_ios: assets/images/logo-dark.png

  android_12:
    image: assets/images/logo-light.png
    icon_background_color: "#CCFD54"
    image_dark: assets/images/logo-dark.png
    icon_background_color_dark: "#5441BF"
  android: true
  ios: true
  web: true
  fullscreen: false
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon-with-bg.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

# dart run flutter_launcher_icons
# dart run flutter_native_splash:create

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/cfg/
    - shorebird.yaml
  fonts:
    - family: TransformaSans
      fonts:
        - asset: assets/fonts/TransformaSans-Medium.ttf
          weight: 600