// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFc5fdPOw10-pipudlhBDk5NdGjsUeQoQ',
    appId: '1:647882782439:android:5082be5a9f627141b15442',
    messagingSenderId: '647882782439',
    projectId: 'grip-10c12',
    storageBucket: 'grip-10c12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI2TTUSVPXZtbIr4xcen5BbbrkDuKPcaU',
    appId: '1:647882782439:ios:284812b9c447d793b15442',
    messagingSenderId: '647882782439',
    projectId: 'grip-10c12',
    storageBucket: 'grip-10c12.appspot.com',
    androidClientId:
        '647882782439-vnu8q6t89un1eht9qoi6lebjo5ivcqui.apps.googleusercontent.com',
    iosClientId:
        '647882782439-agrvhr115sv5ko8alin3hp8vc676sgel.apps.googleusercontent.com',
    iosBundleId: 'com.composir.grip',
  );
}
